const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.DrawingCanvas,
		C3.Plugins.Arr,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Fade,
		C3.Plugins.NinePatch,
		C3.Behaviors.scrollto,
		C3.Behaviors.Physics,
		C3.Behaviors.Sin,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Rotate,
		C3.Plugins.Particles,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.System.Exps.layoutname,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Behaviors.Physics.Acts.CreateDistanceJoint,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Physics.Acts.ApplyTorque,
		C3.Behaviors.Physics.Acts.ApplyForceAtAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.timescale,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Physics.Acts.SetAngularVelocity,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Behaviors.Physics.Acts.SetDensity,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Exps.originalviewportheight,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.originalviewportwidth,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.IsMobile,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Spritefont2.Acts.SetY,
		C3.Plugins.Spritefont2.Exps.Height,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Behaviors.Fade.Cnds.OnFadeInEnd,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.DrawingCanvas.Acts.FillEllipse,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.JavaScriptInEvents.Eads_Event1_Act1
	];
};
self.C3_JsPropNameTable = [
	{Mouse: 0},
	{Touch: 0},
	{Browser: 0},
	{Audio: 0},
	{LocalStorage: 0},
	{DrawingCanvas: 0},
	{Variables: 0},
	{btnMenu: 0},
	{btnReset: 0},
	{Tween: 0},
	{btnSound: 0},
	{Fade: 0},
	{btnStart: 0},
	{running: 0},
	{motor: 0},
	{spring: 0},
	{car: 0},
	{wheel_left: 0},
	{wheel_right: 0},
	{bgLines: 0},
	{flag: 0},
	{win: 0},
	{defeat: 0},
	{nTuto: 0},
	{lastLine: 0},
	{firstLineID: 0},
	{removeLines: 0},
	{nIdex: 0},
	{color: 0},
	{ScrollTo: 0},
	{gameManager: 0},
	{setted: 0},
	{remove: 0},
	{nIndex: 0},
	{oldX: 0},
	{oldY: 0},
	{line: 0},
	{Physics: 0},
	{ball: 0},
	{sacar: 0},
	{hand: 0},
	{line_tuto: 0},
	{propulsor: 0},
	{road: 0},
	{velX: 0},
	{velY: 0},
	{goGame: 0},
	{Sine: 0},
	{taptoplay: 0},
	{tutorial: 0},
	{transition: 0},
	{name: 0},
	{txtUI: 0},
	{txtBtnNivel: 0},
	{bgSelector: 0},
	{btnArrowLeft: 0},
	{btnArrowRight: 0},
	{Nivel: 0},
	{btnNivel: 0},
	{nHoja: 0},
	{cam_selector: 0},
	{pageIndicator: 0},
	{bgWin: 0},
	{btnMoreGames: 0},
	{btnPlay: 0},
	{gameLogo: 0},
	{Rotate: 0},
	{Sine2: 0},
	{confeti: 0},
	{confeti_explosion: 0},
	{splashLogo: 0},
	{Buttons: 0},
	{Lines: 0},
	{CarElements: 0},
	{Level: 0},
	{maxTorque: 0},
	{totStars: 0},
	{GAMENAME_SAVE: 0},
	{TOTLEVELS: 0},
	{layerIn: 0},
	{layerOut: 0},
	{FADESPEED: 0},
	{Layout: 0},
	{newlayer: 0},
	{posX: 0},
	{posY: 0},
	{drawing: 0},
	{drawDistance: 0},
	{smoothingSteps: 0}
];

self.InstanceType = {
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	DrawingCanvas: class extends self.IDrawingCanvasInstance {},
	Variables: class extends self.IArrayInstance {},
	btnMenu: class extends self.ISpriteInstance {},
	btnReset: class extends self.ISpriteInstance {},
	btnSound: class extends self.ISpriteInstance {},
	btnStart: class extends self.ISpriteInstance {},
	car: class extends self.ISpriteInstance {},
	wheel_left: class extends self.ISpriteInstance {},
	wheel_right: class extends self.ISpriteInstance {},
	bgLines: class extends self.I9PatchInstance {},
	flag: class extends self.ISpriteInstance {},
	gameManager: class extends self.ISpriteInstance {},
	line: class extends self.ISpriteInstance {},
	ball: class extends self.ISpriteInstance {},
	hand: class extends self.ISpriteInstance {},
	line_tuto: class extends self.ISpriteInstance {},
	propulsor: class extends self.ISpriteInstance {},
	road: class extends self.I9PatchInstance {},
	spring: class extends self.ISpriteInstance {},
	taptoplay: class extends self.ISpriteInstance {},
	tutorial: class extends self.ISpriteInstance {},
	transition: class extends self.ISpriteInstance {},
	txtUI: class extends self.ISpriteFontInstance {},
	txtBtnNivel: class extends self.ISpriteFontInstance {},
	bgSelector: class extends self.ISpriteInstance {},
	btnArrowLeft: class extends self.ISpriteInstance {},
	btnArrowRight: class extends self.ISpriteInstance {},
	btnNivel: class extends self.ISpriteInstance {},
	cam_selector: class extends self.ISpriteInstance {},
	pageIndicator: class extends self.ISpriteInstance {},
	bgWin: class extends self.ISpriteInstance {},
	btnMoreGames: class extends self.ISpriteInstance {},
	btnPlay: class extends self.ISpriteInstance {},
	gameLogo: class extends self.ISpriteInstance {},
	confeti: class extends self.ISpriteInstance {},
	confeti_explosion: class extends self.IParticlesInstance {},
	splashLogo: class extends self.ISpriteInstance {},
	Buttons: class extends self.ISpriteInstance {},
	Lines: class extends self.ISpriteInstance {},
	CarElements: class extends self.ISpriteInstance {}
}